### ISSUE TITLE
Missing user font paths on Windows

### ISSUE THREAD

**Issue by p0nce** [MyLittleRobo/standardpaths#14]
https://github.com/AuburnSounds/printed/issues/39

On my machine, there are user fonts in `C:\Users\<user>\AppData\Local\Microsoft\Windows\fonts`
however only `c:\Windows\fonts` is returned by `standardPaths(StandardPath.fonts)`, twice.

This leads to errors downstream as people instal fonts just for them and not globally.

**Comment by FreeSlave** [comment]
Windows API does not provide a function to retrieve user fonts directories. I did a bit of research and it seems to be possible to get them from Windows registry via `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts`.
However on Windows fonts are specifically 'installed', so grabbing all fonts from the directory be it a global one or a user one may lead to including fonts that are not really 'installed' but just happen to be in these directories. If one wants to be truly correct it's better to grab the list of installed fonts via registry.
I can add evaluating of user fonts directories, but the evaluating of 'installed' fonts is not a scope of the **standardpaths**.

Including fonts paths in **standardpaths** probably was a mistake from the start. Currently it does not do a proper evaluation of fonts on freedesktop systems either since the correct way would be to parse fonconfig xml files which is again out of the scope of the **standardpaths**.

**Comment by FreeSlave** [comment]
If you're interested in building a list of installed fonts on Windows you may look at [matplotlib font manager code](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/font_manager.py#L139)

**Comment by p0nce** [comment]
Interesting thanks. For now I'm parsing font directories indeed and added the user ones as workaround.

Fonts are embedded in our SVG/PDF output in the general cases with `printed` so finding the OpenType file is enough to guarantee reproducibility (although we do strive to make it close to what a browser would do).
